FROM ubuntu:18.04

# Pra funcionar atrás do proxy da CODEPLAN.
COPY hosts /etc/hosts
COPY resolv.conf /etc/resolv.conf

# Instala pacotes do apt-get.
#RUN ping archive.ubuntu.com -w 3
RUN apt-get -y update && apt-get -y install python3 python3-pip

# Instala pacotes do python.
COPY requirements.txt /var/www/
RUN pip3 install -r /var/www/requirements.txt

# Copiar código inteiro para dentro do container.
COPY . /var/www/geocode
